#!/usr/bin/env python3
"""Render the audio guide with ElevenLabs and write the player manifest.

    ELEVENLABS_KEY_FILE=~/path/to/keyfile python3 tools/voice/generate.py
    (or ELEVENLABS_API_KEY=... — never commit the key; it is only read here.)

Source text: tools/voice/scripts.json  ({id: {setup, tips[]}, _generic: {name: text}})
Output:      audio/voice/<id>.s.mp3, <id>.t1..t4.mp3, _generic clips as <name>.mp3
Manifest:    scripts/data/voice-manifest.js  (clip durations, used for timing)

Re-runs only render clips whose text changed (hash cache in audio/voice/.hashes.json).
Needs ffprobe (ffmpeg) for durations.
"""
import hashlib, json, os, subprocess, sys, time, urllib.request
from concurrent.futures import ThreadPoolExecutor

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SCRIPTS = os.path.join(ROOT, 'tools', 'voice', 'scripts.json')
OUT = os.path.join(ROOT, 'audio', 'voice')
MANIFEST = os.path.join(ROOT, 'scripts', 'data', 'voice-manifest.js')

VOICE_ID = 'pFZP5JQG7iQjIQuC4Bku'   # Lily (British, velvety) — ElevenLabs premade
MODEL = 'eleven_multilingual_v2'
SETTINGS = {'stability': 0.6, 'similarity_boost': 0.75, 'style': 0.0, 'use_speaker_boost': True, 'speed': 0.9}
FORMAT = 'mp3_44100_32'


def api_key():
    k = os.environ.get('ELEVENLABS_API_KEY')
    if not k and os.environ.get('ELEVENLABS_KEY_FILE'):
        k = open(os.path.expanduser(os.environ['ELEVENLABS_KEY_FILE'])).read()
    if not k:
        sys.exit('Set ELEVENLABS_API_KEY or ELEVENLABS_KEY_FILE')
    return k.strip()


def clips(data):
    for name, text in data['_generic'].items():
        yield name, text
    for ex_id, v in data.items():
        if ex_id.startswith('_'):
            continue
        yield f'{ex_id}.s', v['setup']
        for i, t in enumerate(v['tips'], 1):
            yield f'{ex_id}.t{i}', t


def render(key, name, text):
    body = json.dumps({'text': text, 'model_id': MODEL, 'voice_settings': SETTINGS}).encode()
    req = urllib.request.Request(
        f'https://api.elevenlabs.io/v1/text-to-speech/{VOICE_ID}?output_format={FORMAT}', data=body,
        headers={'xi-api-key': key, 'Content-Type': 'application/json', 'Accept': 'audio/mpeg'})
    for attempt in range(5):
        try:
            with urllib.request.urlopen(req, timeout=90) as r:
                data = r.read()
            with open(os.path.join(OUT, name + '.mp3'), 'wb') as f:
                f.write(data)
            return name
        except urllib.error.HTTPError as e:
            if e.code in (429, 500, 502, 503) and attempt < 4:
                time.sleep(2 ** attempt * 2)
                continue
            raise RuntimeError(f'{name}: HTTP {e.code}') from None


def duration(path):
    out = subprocess.run(['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', path],
                         capture_output=True, text=True).stdout.strip()
    return round(float(out), 2)


def main():
    os.makedirs(OUT, exist_ok=True)
    data = json.load(open(SCRIPTS))
    hashes_path = os.path.join(OUT, '.hashes.json')
    hashes = json.load(open(hashes_path)) if os.path.exists(hashes_path) else {}
    todo = []
    for name, text in clips(data):
        h = hashlib.sha1(f'{VOICE_ID}|{MODEL}|{json.dumps(SETTINGS, sort_keys=True)}|{text}'.encode()).hexdigest()
        if hashes.get(name) != h or not os.path.exists(os.path.join(OUT, name + '.mp3')):
            todo.append((name, text, h))
    print(f'{len(todo)} clips to render')
    if todo:
        key = api_key()
        with ThreadPoolExecutor(max_workers=4) as pool:
            futs = {pool.submit(render, key, n, t): (n, h) for n, t, h in todo}
            for i, f in enumerate(futs, 1):
                n, h = futs[f]
                f.result()
                hashes[n] = h
                if i % 25 == 0:
                    print(f'  {i}/{len(todo)}')
                    json.dump(hashes, open(hashes_path, 'w'), indent=0)
        json.dump(hashes, open(hashes_path, 'w'), indent=0)

    manifest = {'generic': {}, 'ex': {}}
    for name in data['_generic']:
        manifest['generic'][name] = duration(os.path.join(OUT, name + '.mp3'))
    for ex_id, v in data.items():
        if ex_id.startswith('_'):
            continue
        manifest['ex'][ex_id] = {
            's': duration(os.path.join(OUT, f'{ex_id}.s.mp3')),
            't': [duration(os.path.join(OUT, f'{ex_id}.t{i}.mp3')) for i in range(1, len(v['tips']) + 1)],
        }
    with open(MANIFEST, 'w') as f:
        f.write('// Generated by tools/voice/generate.py — clip durations (s) for audio-guide timing.\n')
        f.write(f'// Voice: ElevenLabs Lily ({MODEL}), files in audio/voice/.\n')
        f.write('export const VOICE = ' + json.dumps(manifest, separators=(',', ':')) + ';\n')
    print('manifest written:', len(manifest['ex']), 'exercises')


if __name__ == '__main__':
    main()
